name: publish

on:
  push:
    branches: ['main']

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # e.g uomlibrary/web-tei-preview:latest
  IMAGE_NAME: uomlibrary/web-tei-preview:latest

jobs:
  publish:
    name: publish image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Login
        run: |
          echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and Publish
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} --push .

  deploy:
    needs: publish
    name: deploy image
    runs-on: ubuntu-latest

    steps:
      - name: install ssh keys
        # check this thread to understand why its needed:
        # <https://stackoverflow.com/a/70447517>
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: connect and pull
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<EOF
            cd ${{ secrets.WORK_DIR }}
            echo ${{ secrets.PAT }} | docker login ghcr.io -u <username> --password-stdin
            docker compose pull
            docker compose up -d && exit
          EOF
      - name: cleanup
        run: rm -rf ~/.ssh
